# Generated by Django 3.1.2 on 2021-02-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udhaar', '0002_auto_20210206_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='trace',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
